add checks/error logging and remove wget parameter progressbar

diff --git a/data/postgres15/scripts/entrypoint b/data/postgres15/scripts/entrypoint
--- a/data/postgres15/scripts/entrypoint
+++ b/data/postgres15/scripts/entrypoint
@@ -4,6 +4,38 @@ set -Eeuo pipefail
 export POSTGRES_HOST_AUTH_METHOD=scram-sha-256
 export POSTGRES_PASSWORD=$POSTGRES_PASSWORD
 
+RED='\033[0;31m'
+BLUE='\033[0;34m'
+GREEN='\033[0;32m'
+YELLOW='\033[1;33m'
+ORANGE='\033[0;33m'
+NC='\033[0m'
+
+log_info() {
+    msg=$1
+    date=$(date "+%Y-%m-%d %H:%M:%S")
+    echo -e "${BLUE}INFO${NC}[${date}] postgresql_setup: ${msg}"
+}
+
+log_fatal() {
+    msg=$1
+    date=$(date "+%Y-%m-%d %H:%M:%S")
+    echo -e "${RED}FATA${NC}[${date}] postgresql_setup: ${msg}" 1>&2 
+    exit 1
+}
+
+log_warn() {
+    msg=$1
+    date=$(date "+%Y-%m-%d %H:%M:%S")
+    echo -e "${ORANGE}WARN${NC}[${date}] postgresql_setup: ${msg}"
+}
+
+log_err() {
+    msg=$1
+    date=$(date "+%Y-%m-%d %H:%M:%S")
+    echo -e "${RED}ERR${NC}[${date}] postgresql_setup: ${msg}" 1>&2
+}
+
 file_env() {
 	local var="$1"
 	local fileVar="${var}_FILE"
@@ -49,6 +81,8 @@ docker_create_db_directories() {
 			find "$POSTGRES_INITDB_WALDIR" \! -user postgres -exec chown postgres '{}' +
 		fi
 		chmod 700 "$POSTGRES_INITDB_WALDIR"
+		else
+		log_err "Could not create the transaction log directory."
 	fi
 
 	# allow the container to be started with `--user`
